FLASK_SECRET_KEY: "SET A SECRET FLASK SESSION KEY HERE"
EMAIL_PASSWORD: "SET AN EMAIL PASSWORD HERE"
SERVER_CERTIFICATE_FILE: "FULL PATH TO YOUR CRT FILE"
SERVER_KEY_FILE: "FULL PATH TO YOUR KEY FILE"
CONSUMER_KEY_CERT: ""
CONSUMER_KEY_PEM_FILE: "FULL PATH TO YOUR PEM FILE"
CONSUMER_KEY: "SET A CONSUMER KEY FOR YOUR LTI APP"
CONSUMER_KEY_SECRET: "SET A SECRET KEY FOR YOUR LTI APP"
SECURITY_PASSWORD_SALT: "SET A PASSWORD SALT FOR FLASK-SECURITY HERE"